version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:14.16
    working_directory: ~/repo

jobs:
  install_dependencies:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install

  deploy_to_render:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Trigger Render Deployment
          command: |
            echo "Deploying to Render..."
            curl -X POST ${RENDER_DEPLOY_HOOK}

workflows:
  version: 2
  deploy_on_tag:
    jobs:
      - install_dependencies:
          filters:
            tags:
              only:
                - /^v\d+\.\d+\.(\d{3}|\d{2}|\d{1}).*$/
            branches:
              ignore: /.*/
      - deploy_to_render:
          requires:
            - install_dependencies
          filters:
            tags:
              only:
                - /^v\d+\.\d+\.(\d{3}|\d{2}|\d{1}).*$/
            branches:
              ignore: /.*/
